/**
 * Copyright (c) 2003, 2026 IBM Corporation and others.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   IBM - Initial API and implementation
 *   Obeo - Extract from TestBase into separate class
 */
package org.eclipse.emf.validation.tests;

import static org.junit.Assert.fail;

import java.util.Arrays;
import java.util.Collection;

import org.eclipse.core.runtime.IStatus;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.validation.model.IConstraintStatus;
import org.eclipse.emf.validation.model.IModelConstraint;

/**
 * Common assertions useful for EMF Validation tests.
 */
public final class Assertions {
	/**
	 * Helper method that asserts that none of the specified constraints were
	 * retrieved by the service.
	 *
	 * @param constraintType the type of constraint (batch, live, feature)
	 * @param statuses       the constraint statuses that resulted from validation
	 * @param ids            the taboo constraint IDs
	 */
	public static void assertAllConstraintsNotPresent(String constraintType, IStatus[] statuses, String... ids) {
		Collection<String> found = new java.util.ArrayList<>();

		for (IStatus element : statuses) {
			IModelConstraint next = ((IConstraintStatus) element).getConstraint();
			String id = next.getDescriptor().getId();
			if (Arrays.asList(ids).contains(id)) {
				found.add(id);
			}
		}

		if (!found.isEmpty()) {
			fail(String.format("Found unwanted %s constraints: %s", constraintType, found));
		}
	}

	/**
	 * Helper method that asserts that none of the specified constraints were
	 * retrieved from a specific provider.
	 *
	 * @param constraintType the type of constraint (batch, live, feature)
	 * @param constraints    the constraints obtained from the provider
	 * @param ids            the taboo constraint IDs
	 */
	public static void assertAllConstraintsNotPresent(String constraintType, Collection<IModelConstraint> constraints,
			String... ids) {
		Collection<String> found = new java.util.ArrayList<>();

		for (IModelConstraint next : constraints) {
			String id = next.getDescriptor().getId();
			if (Arrays.asList(ids).contains(id)) {
				found.add(id);
			}
		}

		if (!found.isEmpty()) {
			fail(String.format("Found unwanted %s constraints: %s", constraintType, found));
		}
	}

	/**
	 * Helper method that asserts that all specified constraints were retrieved by
	 * the service.
	 *
	 * @param constraintType the type of constraint (batch, live, feature)
	 * @param statuses       the constraint statuses that resulted from validation
	 * @param ids            the expected constraint IDs
	 */
	public static void assertAllConstraintsPresent(String constraintType, IStatus[] statuses, String... ids) {
		Collection<String> notFound = new java.util.LinkedList<>(Arrays.asList(ids));

		for (IStatus element : statuses) {
			IModelConstraint next = ((IConstraintStatus) element).getConstraint();
			notFound.remove(next.getDescriptor().getId());
		}

		if (!notFound.isEmpty()) {
			fail(String.format("Did not find %s constraints: %s", constraintType, notFound));
		}
	}

	/**
	 * Helper method that asserts that all specified constraints were retrieved from
	 * a specific provider.
	 *
	 * @param constraintType the type of constraint (batch, live, feature)
	 * @param constraints    the constraints obtained from the provider
	 * @param ids            the expected constraint IDs
	 */
	public static void assertAllConstraintsPresent(String constraintType, Collection<IModelConstraint> constraints,
			String... ids) {
		Collection<String> notFound = new java.util.LinkedList<>(Arrays.asList(ids));

		for (IModelConstraint next : constraints) {
			notFound.remove(next.getDescriptor().getId());
		}

		if (!notFound.isEmpty()) {
			fail(String.format("Did not find %s constraints: %s", constraintType, notFound));
		}
	}

	/**
	 * Helper method that asserts that all specified targets has status reports
	 * generated by the service.
	 *
	 * @param constraintType the type of constraint (batch, live, feature)
	 * @param statuses       the constraint statuses that resulted from validation
	 * @param targets        the expected target objects
	 */
	public static void assertAllTargetsPresent(String constraintType, IStatus[] statuses,
			Collection<? extends EObject> targets) {
		Collection<EObject> notFound = new java.util.LinkedList<>(targets);

		for (IStatus element : statuses) {
			IConstraintStatus next = (IConstraintStatus) element;
			notFound.remove(next.getTarget());
		}

		if (!notFound.isEmpty()) {
			fail(String.format("Did not find %s targets: %s", constraintType, notFound));
		}
	}

	public static void assertConstraintAndTargetNotPresent(String constraintType, IStatus[] statuses,
			String constraintId, EObject target) {
		for (IStatus element : statuses) {
			IConstraintStatus status = (IConstraintStatus) element;
			IModelConstraint constraint = ((IConstraintStatus) element).getConstraint();

			if (target.equals(status.getTarget()) && constraintId.equals(constraint.getDescriptor().getId())) {
				fail(String.format("Found unwanted %s constraint %s on %s", constraintType, constraintId, target));
			}
		}
	}

	public static void assertConstraintAndTargetPresent(String constraintType, IStatus[] statuses, String constraintId,
			EObject target) {
		for (IStatus element : statuses) {
			IConstraintStatus status = (IConstraintStatus) element;
			IModelConstraint constraint = ((IConstraintStatus) element).getConstraint();

			if (target.equals(status.getTarget()) && constraintId.equals(constraint.getDescriptor().getId())) {
				return;
			}
		}
		fail(String.format("Did not find %s constraint %s on %s", constraintType, constraintId, target));
	}

}
