<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ordersystem"
    nsURI="http:///ordersystem.ecore" nsPrefix="ordersystem">
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placedOn" eType="#//JavaDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filledOn" eType="#//JavaDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Customer"
        transient="true" eOpposite="#//Customer/order"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//LineItem"
        containment="true" eOpposite="#//LineItem/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sku" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//OrderSystem"
        transient="true" eOpposite="#//OrderSystem/product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Warehouse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//OrderSystem"
        transient="true" eOpposite="#//OrderSystem/warehouse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//InventoryItem"
        containment="true" eOpposite="#//InventoryItem/Warehouse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Address" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" upperBound="-1"
        eType="#//Customer" containment="true" eOpposite="#//Customer/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" upperBound="-1"
        eType="#//Product" containment="true" eOpposite="#//Product/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="warehouse" upperBound="-1"
        eType="#//Warehouse" containment="true" eOpposite="#//Warehouse/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineItem">
    <eOperations name="getCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Order"
        transient="true" eOpposite="#//Order/item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JavaDate" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EClass" name="InventoryItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restockThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStockDate" eType="#//JavaDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Warehouse" eType="#//Warehouse"
        transient="true" eOpposite="#//Warehouse/item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//OrderSystem"
        transient="true" eOpposite="#//OrderSystem/customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" upperBound="-1"
        eType="#//Account" containment="true" eOpposite="#//Account/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" upperBound="-1"
        eType="#//Order" containment="true" eOpposite="#//Order/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apartment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="province" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Customer"
        transient="true" eOpposite="#//Customer/account"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billingAddress" lowerBound="1"
        eType="#//Address" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shippingAddress" lowerBound="1"
        eType="#//Address" containment="true"/>
  </eClassifiers>
  <eSubpackages name="special" nsURI="http:///ordersystem/special.ecore" nsPrefix="ordersystem.special">
    <eClassifiers xsi:type="ecore:EClass" name="PreferredCustomer" eSuperTypes="#//Customer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="since" eType="#//JavaDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LimitedEditionProduct" eSuperTypes="#//Product">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableUntil" eType="#//JavaDate"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
