name: Generate and ingest SBOM into sbom.eclipse.org

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.build.outputs.PROJECT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build
        id: build
        run: |
          ./mvnw -B -ntp clean package
          VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          mv releng/org.eclipse.emf.validation.repository/target/bom.json emf-validation-bom.json
      - name: Upload sbom
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: sbom
          path: emf-validation-bom.json

  store-sbom-data: # stores sbom and metadata in a predefined format for otterdog to pick up
    needs: ['build']
    uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
    with:
      projectName: 'EMF Validation'
      projectVersion: ${{ needs.build.outputs.project-version }}
      bomArtifact: 'sbom'
      bomFilename: 'emf-validation-bom.json'
      parentProject: 'aa5345ed-b2c4-45db-83cf-166ad9dfd0f9'
