name: Generate and ingest SBOM into sbom.eclipse.org

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.build.outputs.PROJECT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build
        id: build
        run: |
          ./mvnw -B -ntp clean package
          VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          mv releng/org.eclipse.emf.validation.repository/target/bom.json emf-validation-bom.json
      - name: Upload sbom
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom
          path: emf-validation-bom.json

  store-sbom-data: # stores sbom and metadata in a predefined format for otterdog to pick up
    needs: ['build']
    uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
    with:
      projectName: 'EMF Validation'
      projectVersion: ${{ needs.build.outputs.project-version }}
      bomArtifact: 'sbom'
      bomFilename: 'emf-validation-bom.json'
      parentProject: 'aa5345ed-b2c4-45db-83cf-166ad9dfd0f9'
