name: Generate and ingest SBOM into sbom.eclipse.org

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build
        id: build
        run: |
          ./mvnw -B -ntp clean package
          VERSION=$(./mvnw -q help:evaluate -Dexpression=project.version -DforceStdout 2> /dev/null | sed -e 's/-SNAPSHOT//')
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          mv releng/org.eclipse.emf.validation.repository/target/bom.json emf-validation-bom.json
      - name: Upload sbom
        uses: eclipse-csi/workflows/upload-sbom@0c1c6cf5cb4dc624a86410274c71b27d6273385a # main
        with:
          sbom-file: emf-validation-bom.json
          product-name: 'EMF Validation'
          product-version: ${{ steps.build.outputs.PROJECT_VERSION }}
